nois :
	clang++ tank.cpp -o tank -lGLEW -lglut -lm -lSOIL -framework Cocoa -framework OpenGL -framework IOKit -framework CoreVideo -lm -lSOIL -I/usr/local/include/GLFW -lglfw3 ../common/InitShader.cpp ../common/iniciaGLEW.cpp ../common/iniciaGLFW.cpp ../common/objloader.cpp
	./tank

